language: php

php:
  - 5.6

env:
  global:
    - PATH=$PATH:/home/travis/.composer/vendor/bin

install:
  - composer self-update
  - composer install

script:
  - cd $TRAVIS_BUILD_DIR
  - ./vendor/bin/grumphp run

notifications:
  email: false
